import numpy as np
import matplotlib.pyplot as plt

print("⚛️ Nuclear Medicine Physics: Gamma Camera Position Decoding Matrix Online ⚛️")

# =====================================================================
# 1. HARDWARE MATRIX FIELD SETUPS (Slab Size in mm)
# =====================================================================
CRYSTAL_SIZE_MM = 400.0       # Dimensions of the square Sodium Iodide (NaI) crystal slab
LIGHT_ATTENUATION_COEFF = 0.015 # Exponential light spread decay factor inside the crystal medium

# Fixed physical spatial coordinates of our 4 quadrant Photomultiplier Tubes (PMTs)
PMT_LEFT_X,  PMT_LEFT_Y   = -200.0, 0.0
PMT_RIGHT_X, PMT_RIGHT_Y  = 200.0,  0.0
PMT_TOP_X,   PMT_TOP_Y    = 0.0,    200.0
PMT_BOTTOM_X, PMT_BOTTOM_Y = 0.0,   -200.0

# =====================================================================
# SYSTEM EXCITATION PARAMETER INPUTS (Radiation Impact Point)
# =====================================================================
try:
    print("\n--- Position a Synthetic Isotope Gamma Ray Target Striking the NaI Crystal ---")
    true_x = float(input("Enter True X-axis radiation impact coordinate (-180 to 180 mm): "))
    true_y = float(input("Enter True Y-axis radiation impact coordinate (-180 to 180 mm): "))
    
    # Secure parameters inside safe physical boundary scales
    true_x = max(-180.0, min(180.0, true_x))
    true_y = max(-180.0, min(180.0, true_y))
except ValueError:
    print("❌ Input Validation Error: Defaulting to a central tumor hot-spot coordinate (+45.0, -60.0).")
    true_x, true_y = 45.0, -60.0

# =====================================================================
# 2. MODEL PHYSICAL OPTICAL LIGHT SPREAD TO THE PMT ARRAY
# =====================================================================
# Calculate Euclidean distances from the gamma ray impact site to each sensor channel face
dist_left   = np.sqrt((true_x - PMT_LEFT_X)**2   + (true_y - PMT_LEFT_Y)**2)
dist_right  = np.sqrt((true_x - PMT_RIGHT_X)**2  + (true_y - PMT_RIGHT_Y)**2)
dist_top    = np.sqrt((true_x - PMT_TOP_X)**2    + (true_y - PMT_TOP_Y)**2)
dist_bottom = np.sqrt((true_x - PMT_BOTTOM_X)**2 + (true_y - PMT_BOTTOM_Y)**2)

# Simulating light spread attenuation: Shorter distance generates higher photomultiplier tube voltages
# Max peak energy scaling factor modeled at 100.0 millivolts
V_left   = 100.0 * np.exp(-LIGHT_ATTENUATION_COEFF * dist_left)
V_right  = 100.0 * np.exp(-LIGHT_ATTENUATION_COEFF * dist_right)
V_top    = 100.0 * np.exp(-LIGHT_ATTENUATION_COEFF * dist_top)
V_bottom = 100.0 * np.exp(-LIGHT_ATTENUATION_COEFF * dist_bottom)

print(f"\n📡 PMT Sensor Board Matrix Return Voltages:")
print(f"  • Channel Left: {V_left:.2f} mV  | Channel Right: {V_right:.2f} mV")
print(f"  • Channel Top:  {V_top:.2f} mV  | Channel Bottom: {V_bottom:.2f} mV")

# =====================================================================
# 3. APPLY TRADITIONAL ANGER LOGIC ALGEBRAIC EQUATIONS
# =====================================================================
# Sum total energy signal (Z pulse) generated by the scintillation flash
Z_pulse_energy = V_left + V_right + V_top + V_bottom

print(f"\n⚡ Total Z-Pulse Scintillation Energy Extracted: {Z_pulse_energy:.2f} mV")

# Anger Logic Coordinate Reconstruction Positioning Computations
# X = ScaleFactor * (V_right - V_left) / TotalEnergy
# Y = ScaleFactor * (V_top - V_bottom) / TotalEnergy
# Empirical hardware scale alignment multiplier constant set at 280.0 for spatial calibration
scale_factor = 280.0
reconstructed_x = scale_factor * (V_right - V_left) / Z_pulse_energy
reconstructed_y = scale_factor * (V_top - V_bottom) / Z_pulse_energy

# Calculate absolute positioning calibration calculation error metrics
position_error_mm = np.sqrt((true_x - reconstructed_x)**2 + (true_y - reconstructed_y)**2)

print("\n--- ☢️ HARDWARE COORD COORDINATE DECODING METRICS ---")
print(f"🎯 Target Location  : X: {true_x:+.1f} mm | Y: {true_y:+.1f} mm")
print(f"🔮 Reconstructed Coords: X: {reconstructed_x:+.1f} mm | Y: {reconstructed_y:+.1f} mm")
print(f"📏 Algebraic Matrix Error Scale: {position_error_mm:.3f} mm Drift Variance Accuracy.")

# =====================================================================
# 4. NUCLEAR INJECT MAP SPATIAL VISUALIZATION
# =====================================================================
print("📊 Compiling Scintillation Spatial Coordinates Localization Graph...")
plt.figure(figsize=(7, 7))

# Draw square NaI Crystal boundary limits
plt.xlim(-220, 220)
plt.ylim(-220, 220)
plt.axhline(0, color='#44444e', linestyle=':', alpha=0.5)
plt.axvline(0, color='#44444e', linestyle=':', alpha=0.5)

# Plot physical positions of PMT array sensors
plt.scatter([PMT_LEFT_X, PMT_RIGHT_X, PMT_TOP_X, PMT_BOTTOM_X], 
            [PMT_LEFT_Y, PMT_RIGHT_Y, PMT_TOP_Y, PMT_BOTTOM_Y], 
            color='#3498db', s=130, marker='s', zorder=3, label='Calibrated PMT Channel Array Sensors')

# Plot true vs reconstructed radiation markers
plt.scatter(true_x, true_y, color='#2ecc71', s=100, marker='o', zorder=4, label='True Gamma Impact Site')
plt.scatter(reconstructed_x, reconstructed_y, color='#e74c3c', s=100, marker='x', linewidths=2.5, zorder=5, label='Anger Logic Reconstructed Site')

# Draw vector error offset ray line
plt.plot([true_x, reconstructed_x], [true_y, reconstructed_y], color='#f1c40f', linestyle='--', linewidth=1.5, label='Spatial Matrix Error Offset')

plt.title('Nuclear Medicine Physics: Gamma Camera Crystal Scintillation Matrix Mapping', fontsize=11, fontweight='bold', pad=15)
plt.xlabel('Lateral Crystal Field Dimension X (mm)', fontweight='bold')
plt.ylabel('Axial Crystal Field Dimension Y (mm)', fontweight='bold')
plt.legend(loc='lower left', prop={'size': 9})
plt.grid(True, linestyle=':', alpha=0.3)

# Enforce your personal KapoleiBioForge dark theme brand layout parameters
plt.gcf().patch.set_facecolor('#1e1e24')
plt.gca().set_facecolor('#2d2d35')
plt.gca().xaxis.label.set_color('white')
plt.gca().yaxis.label.set_color('white')
plt.gca().title.set_color('white')
plt.gca().tick_params(colors='white')
for spine in plt.gca().spines.values():
    spine.set_color('#44444e')

plt.tight_layout()
plt.show()
